### ISSUE TITLE
1. Create new  WebHost named class. And Add HttpListener as property.

### ISSUE THREAD

**Issue by 0605AbMu** [G1-Group/TCB.DevKings#162]
1. Create new  WebHost named class. And Add HttpLister as private property.

_Originally posted by @0605AbMu in https://github.com/G1-Group/TCB.DevKings/issues/161#issuecomment-1692070232_

**Comment by 0605AbMu** [comment]
Get instance from HttpListener with params as prefix parameter that given by constructor

**Comment by MalikaRasulova** [comment]
WebHost added
