### ISSUE TITLE
Get instance from HttpListener with params as prefix parameter that given by constructor. it is in WebHost

### ISSUE THREAD

**Issue by 0605AbMu** [G1-Group/TCB.DevKings#163]
Get instance from HttpListener with params as prefix parameter that given by constructor into initialize named method

_Originally posted by @0605AbMu in https://github.com/G1-Group/TCB.DevKings/issues/162#issuecomment-1692073835_

**Comment by norovferuzbek3963** [comment]
Ustoz bu issua nima qilishini tushuntirvoring ingilischada tarjimasi chiqmayapti yaxshi

**Comment by 0605AbMu** [comment]
Initialize method yasang. Using ichida HttpListener class dan object lib property ga set qiling. Unga kerak bo'ladigan prefix larni tashqai muhitdan oling

**Comment by norovferuzbek3963** [comment]
Ustoz qaysi classni ichida buladi method
