### ISSUE TITLE
Implement middlewares chaining

### ISSUE THREAD

**Issue by 0605AbMu** [G1-Group/TCB.DevKings#168]
If you want use LinkedListNode

**Comment by TatuEconomist2021** [comment]
![photo_2023-08-25_15-12-44](https://github.com/G1-Group/TCB.DevKings/assets/131686173/6b07f248-7311-4ed3-a5ad-78ee8dfeed28)

Ustoz men Middleware ni implement qilishim uchun yangi klass ochib qilamanmi yoki WebHost klasini ichiga implement qilsam ham bo'ladimi
